name: bootcampai
channels:
  - conda-forge
dependencies:
  - python=3.5
  - pandas
  - numpy
  - keras
  - tensorflow-gpu
  - matplotlib
  - scipy
  - Pillow
  pip:
    - git+https://www.github.com/keras-team/keras-contrib.git
